/* eslint-disable */
/* ⚠️ DO NOT EDIT ⚠️ */
/* This file is automatically generated, run 'yarn codegen' to update */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  JSON: { input: any; output: any; }
};

export type AccessToken = {
  __typename?: 'AccessToken';
  access_token?: Maybe<Scalars['String']['output']>;
  expires_in?: Maybe<Scalars['String']['output']>;
  id_token?: Maybe<Scalars['String']['output']>;
};

export type Ingredient = {
  __typename?: 'Ingredient';
  amount: Scalars['String']['output'];
  dilution: Scalars['String']['output'];
  price: Scalars['String']['output'];
  title: Scalars['String']['output'];
  unit: Scalars['String']['output'];
  usedAmount?: Maybe<Scalars['Float']['output']>;
};

export type IngredientInput = {
  amount: Scalars['String']['input'];
  dilution: Scalars['String']['input'];
  price: Scalars['String']['input'];
  title: Scalars['String']['input'];
  unit: Scalars['String']['input'];
  usedAmount?: InputMaybe<Scalars['Float']['input']>;
};

export type IngredientList = {
  __typename?: 'IngredientList';
  author?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  id: Scalars['String']['output'];
  identityStars: Scalars['Int']['output'];
  items?: Maybe<Array<Maybe<Ingredient>>>;
  meta?: Maybe<IngredientMeta>;
  published: Scalars['Boolean']['output'];
  stars: Scalars['Int']['output'];
  title: Scalars['String']['output'];
};


export type IngredientListIdentityStarsArgs = {
  identity?: InputMaybe<Scalars['String']['input']>;
};

export type IngredientListHandle = {
  __typename?: 'IngredientListHandle';
  id: Scalars['ID']['output'];
  token: Scalars['ID']['output'];
};

export type IngredientListInput = {
  desc?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<IngredientInput>>>;
  title: Scalars['String']['input'];
};

export type IngredientListMetaInput = {
  author?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  identity: Scalars['String']['input'];
  name: Scalars['String']['input'];
};

export type IngredientMeta = {
  __typename?: 'IngredientMeta';
  identity: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  approveList?: Maybe<Success>;
  identify?: Maybe<WebGptToken>;
  publishList?: Maybe<IngredientListHandle>;
  refreshToken?: Maybe<WebGptToken>;
  starList: Scalars['Int']['output'];
  swapToken?: Maybe<WebGptToken>;
};


export type MutationApproveListArgs = {
  listId: Scalars['String']['input'];
};


export type MutationIdentifyArgs = {
  provider?: InputMaybe<Providers>;
  providerToken: OAuthCode;
};


export type MutationPublishListArgs = {
  list?: InputMaybe<IngredientListInput>;
  meta?: InputMaybe<IngredientListMetaInput>;
};


export type MutationRefreshTokenArgs = {
  previousAccessToken?: InputMaybe<WebGptTokenInput>;
};


export type MutationStarListArgs = {
  identity: Scalars['String']['input'];
  listId: Scalars['String']['input'];
};


export type MutationSwapTokenArgs = {
  provider?: InputMaybe<Providers>;
  providerToken: OAuthCode;
  webGPTToken?: InputMaybe<WebGptTokenInput>;
};

export type OAuthCode = {
  code: Scalars['String']['input'];
};

export enum Providers {
  Google = 'GOOGLE',
  Reddit = 'REDDIT'
}

export type Query = {
  __typename?: 'Query';
  getStars: Scalars['Int']['output'];
  listFormulas?: Maybe<Array<Maybe<IngredientList>>>;
  retrieve?: Maybe<Scalars['String']['output']>;
  searchFormulas?: Maybe<SearchFormulaResult>;
};


export type QueryGetStarsArgs = {
  identity?: InputMaybe<Scalars['String']['input']>;
  listId: Scalars['String']['input'];
};


export type QueryRetrieveArgs = {
  token?: InputMaybe<WebGptTokenInput>;
};


export type QuerySearchFormulasArgs = {
  q?: InputMaybe<Scalars['String']['input']>;
};

export type SearchFormulaResult = {
  __typename?: 'SearchFormulaResult';
  items?: Maybe<Array<Maybe<IngredientList>>>;
  q: Scalars['String']['output'];
};

export type Success = {
  __typename?: 'Success';
  status: Scalars['String']['output'];
};

export type WebGptToken = {
  __typename?: 'WebGPTToken';
  GOOGLE?: Maybe<AccessToken>;
  REDDIT?: Maybe<AccessToken>;
  exp: Scalars['String']['output'];
  signed: Scalars['String']['output'];
};

export type WebGptTokenInput = {
  access_token: Scalars['String']['input'];
};
