export const images = [
  "/images/wallpaper/bg.jpeg",
  "/images/wallpaper/bg.1.jpeg",
  "/images/wallpaper/bg.2.jpeg",
  "/images/wallpaper/bg.3.jpeg",
  "/images/wallpaper/bg.4.jpeg",
  "/images/wallpaper/bg.5.jpeg",
  "/images/wallpaper/bg.6.jpeg",
  "/images/wallpaper/bg.7.jpeg",
  "/images/wallpaper/bg.8.jpeg",
  "/images/wallpaper/bg.orange.1.jpeg",
];

export const ingredients = {
  "Oud Assafi™": "/images/ingredients/oud-assafi.jpeg",
  "Orange Flower Absolute": "/images/ingredients/orange-flower-absolute.jpeg",
  Geosmin: "/images/ingredients/Geosmin.jpeg",
  "Rose Oil, Bulgarian P&N": "/images/ingredients/RoseOilPN.jpeg",
  "Tuberose Absolute": "/images/ingredients/TuberoseAbsolute.jpeg",
  "Orris Butter Tincture": "/images/ingredients/OrrisButterTincture.jpeg",
  "Clearwood®": "/images/ingredients/Clearwood.jpeg",
  "Iso E Super": "/images/ingredients/ISOESuper.jpeg",
  "Woody Base (Pellwall)": "/images/ingredients/WoodyBase.jpeg",
  Koavone: "/images/ingredients/Koavone.jpeg",
  Bornafix: "/images/ingredients/Bornafix.jpeg",
  Timbersilk: "/images/ingredients/Timbersilk.jpeg",
  "BHT Crystals": "/images/ingredients/BHTCrystals.jpeg",
  Veramoss: "/images/ingredients/Veramoss.jpeg",
  "1-Octen-3-ol": "/images/ingredients/1Octen3ol.jpeg",
  "Castoreum Absolute": "/images/ingredients/Castoreum.jpeg",
  "Neroli Tunisia P&N": "/images/ingredients/NeroliTunisiaPN.jpeg",
  Civettone: "/images/ingredients/Civettone.jpeg",
  "Ysamber K": "/images/ingredients/YSamberK.jpeg",
  "Vetiveryl Acetat": "/images/ingredients/VetiverylAcetat.jpeg",
  "Aldehyde C-10": "/images/ingredients/AldehydC10.jpeg",
  "Aldehyde C-12 MNA": "/images/ingredients/AldehydC12.jpeg",
  "Aldehyde C-8": "/images/ingredients/AldehydC8.jpeg",
  Amarocit: "/images/ingredients/Amarocit.jpeg",
  "Amber Xtreme": "/images/ingredients/AmberXtreme.jpeg",
  Ambercore: "/images/ingredients/AmberCore.jpeg",
  "Ambergris T Oliffac": "/images/ingredients/Ambergris.jpeg",
  Ambrettolide: "/images/ingredients/Ambrettolide.jpeg",
  Ambroxan: "/images/ingredients/Ambroxan.jpeg",
  Aphermate: "/images/ingredients/Aphermate.jpeg",
  Aquaflor: "/images/ingredients/Aquaflor.jpeg",
  "Beeswax Absolute": "/images/ingredients/BeeswaxAbsolute.jpeg",
  "Bergamot - Essential Oil - Calabria, IT":
    "/images/ingredients/BergamotEO.jpeg",
  "Beta Pinene": "/images/ingredients/BetaPinene.jpeg",
  "Beyond Hivernal": "/images/ingredients/BeyondHivernal.jpeg",
  "Birch Tar (Rectified)": "/images/ingredients/BirchTar.jpeg",
  "Black Hemlock Absolute": "/images/ingredients/BlackHemlock.jpeg",
  "Blackcurrant Absolute": "/images/ingredients/BlackcurrantAbsolute.jpeg",
  "Bran Absolute": "/images/ingredients/BranAbsolute.jpeg",
  "Broom Absolute": "/images/ingredients/BroomAbsolute.jpeg",
  Calone: "/images/ingredients/Calone.jpeg",
  Cashmeran: "/images/ingredients/Cashmeran.jpeg",
  "Cedarwood EO": "/images/ingredients/CedarwoodEO.jpeg",
  "Cedryl Acetat": "/images/ingredients/CedrylAcetat.jpeg",
  Celestolide: "/images/ingredients/Celestolide.jpeg",
  "Cis-3-hexen-1-ol": "/images/ingredients/LeafAlcohol.jpeg",
  "Cistus Oil": "/images/ingredients/CistusOil.jpeg",
  "Civet Absolute": "/images/ingredients/CivetAbsolute.jpeg",
  "Costus Oliffac": "/images/ingredients/CostusOliffac.jpeg",
  Coumarin: "/images/ingredients/Coumarin.jpeg",
  "Cypress EO": "/images/ingredients/CypressEO.jpeg",
  "Dirt Fragrance Oil": "/images/ingredients/DirtFragranceOil.jpeg",
  Dowanol: "/images/ingredients/Dowanol.jpeg",
  "Ethylene Brassylate": "/images/ingredients/EthyleneBrassylate.jpeg",
  "Eucalyptus Bioabsolute": "/images/ingredients/EucalyptusBioabsolute.jpeg",
  Evernyl: "/images/ingredients/Evernyl.jpeg",
  Exaltolide: "/images/ingredients/Exaltolide.jpeg",
  Farnesol: "/images/ingredients/Farnesol.jpeg",
  "Fir Balsam": "/images/ingredients/FirBalsam.jpeg",
  "Fixateur 505E": "/images/ingredients/Fixateur505E.jpeg",
  Ozofleur: "/images/ingredients/Ozofleur.jpeg",
  Floralozone: "/images/ingredients/Floralozone.jpeg",
  Galaxolide: "/images/ingredients/Galaxolide.jpeg",
  "Galbanum Oil": "/images/ingredients/GalbanumOil.jpeg",
  "Galbanum Resinoid": "/images/ingredients/GalbanumResinoid.jpeg",
  Habanolide: "/images/ingredients/Habanolide.jpeg",
  Hedione: "/images/ingredients/Hedione.jpeg",
  "Hedione HC": "/images/ingredients/HedioneHC.jpeg",
  Helional: "/images/ingredients/Helional.jpeg",
  "Heliotropin Replacer": "/images/ingredients/HeliotropinReplacer.jpeg",
  Hivernal: "/images/ingredients/Hivernal.jpeg",
  Iralia: "/images/ingredients/Iralia.jpeg",
  Isolongifolanone: "/images/ingredients/Isolongifolanone.jpeg",
  "Jasmine Grandiflorum Absolute":
    "/images/ingredients/JasmineGrandiflorumAbsolute.jpeg",
  "Jasmine Sambac Absolute": "/images/ingredients/JasmineSambacAbsolute.jpeg",
  Kephalis: "/images/ingredients/Kephalis.jpeg",
  "Labdanum Absolute": "/images/ingredients/LabdanumAbsolute.jpeg",
  "Lavender Absolute": "/images/ingredients/LavenderAbsolute.jpeg",
  "Lavender EO": "/images/ingredients/LavenderEO.jpeg",
  Linalool: "/images/ingredients/Linalool.jpeg",
  "Linalool Oxide": "/images/ingredients/LinaloolOxide.jpeg",
  Maritima: "/images/ingredients/Maritima.jpeg",
  "Mate Absolute": "/images/ingredients/MateAbsolute.jpeg",
  "Methyl Anthranilate": "/images/ingredients/MethylAnthranilate.jpeg",
  "Methyl Ionone Gamma": "/images/ingredients/MethylIononeGamma.jpeg",
  "Methyl Laitone": "/images/ingredients/MethylLaitone.jpeg",
  "Mimosa Olessence": "/images/ingredients/MimosaOlessence.jpeg",
  Muscenone: "/images/ingredients/Muscenone.jpeg",
  "Musk Blend (Pellwall)": "/images/ingredients/MuskBlend.jpeg",
  "Musk Ketone": "/images/ingredients/MuskKetone.jpeg",
  "Myrrh Oil": "/images/ingredients/MyrrhOil.jpeg",
  "Oakmoss Absolute": "/images/ingredients/OakmossAbsolute.jpeg",
  "Oakwood Absolute": "/images/ingredients/OakwoodAbsolute.jpeg",
  "Octyl Acetate": "/images/ingredients/OctylAcetate.jpeg",

  "Olibanum Absolute": "/images/ingredients/OlibanumAbsolute.jpeg",
  "Olibanum EO": "/images/ingredients/OlibanumEO.jpeg",
  "Orange Flower Blend": "/images/ingredients/OrangeFlowerBlend.jpeg",
  Padma: "/images/ingredients/PADMA.jpeg",
  "Patchouli EO": "/images/ingredients/PatchouliEO.jpeg",
  "Patchouli Light EO": "/images/ingredients/PatchouliLightEO.jpeg",
  "Pine Needles EO": "/images/ingredients/PineNeedlesEO.jpeg",

  "Pino Acetaldehyde": "/images/ingredients/PinoAcetaldehyde.jpeg",
  "Precyclemone B": "/images/ingredients/PrecyclemoneB.jpeg",
  "Rose Givco 217": "/images/ingredients/RoseGivco217.jpeg",
  "Sandalwood EO": "/images/ingredients/SandalwoodEO.jpeg",
  "Sandalwood Mysore": "/images/ingredients/SandalwoodMysore.jpeg",
  Scentenal: "/images/ingredients/Scentenal.jpeg",
  "Seaweed Absolute": "/images/ingredients/SeaweedAbsolute.jpeg",
  Sylvamber: "/images/ingredients/Sylvamber.jpeg",
  Terrasol: "/images/ingredients/Terrasol.jpeg",
  "Timbrox Base": "/images/ingredients/TimbroxBase.jpeg",
  "Tolu Balsam Essence": "/images/ingredients/ToluBalsamEssence.jpeg",

  Tonalid: "/images/ingredients/Tonalid.jpeg",
  Trital: "/images/ingredients/Trital.jpeg",
  Velvione: "/images/ingredients/Velvione.jpeg",
  Vernaldehyde: "/images/ingredients/Vernaldehyde.jpeg",
  Vertenex: "/images/ingredients/Vertenex.jpeg",
  "Vertofix Coeur": "/images/ingredients/VertofixCoeur.jpeg",
  Vetikone: "/images/ingredients/Vetikone.jpeg",
  "Violet Leaf Absolute": "/images/ingredients/VioletLeafAbsolute.jpeg",
  "Z11 10 MIP": "/images/ingredients/Z1110MIP.jpeg",
  "1,3 Propanediol": "/images/ingredients/13Propanediol.jpeg",
  "5-Methyl-2-Phenyl-2-Hexenal":
    "/images/ingredients/5-Methyl-2-Phenyl-2-Hexenal.jpeg",
  Acetal: "/images/ingredients/Acetal.jpeg",
  "Acetaldehyde ethyl linalyl acetal":
    "/images/ingredients/AcetaldehydeEthylLinalylAcetal.jpeg",
  "Acetanisole Crystals": "/images/ingredients/AcetanisoleCrystals.jpeg",
  "Acetate C-8": "/images/ingredients/AcetateC8.jpeg",
  "Acetate C9": "/images/ingredients/AcetateC9.jpeg",
  "Acetic Acid": "/images/ingredients/AceticAcid.jpeg",
  Acetophenone: "/images/ingredients/Acetophenone.jpeg",
  Adoxal: "/images/ingredients/Adoxal.jpeg",
  Acetanisole: "/images/ingredients/Acetanisole.jpeg",
} as Record<string, string>;

export const thumbnails = {
  "Oud Assafi™": "/images/ingredients/oud-assafi.jpeg",
  "Orange Flower Absolute": "/images/ingredients/orange-flower-absolute.jpeg",
  Geosmin: "/images/ingredients/Geosmin.jpeg",
  "Rose Oil, Bulgarian P&N": "/images/ingredients/RoseOilPN.jpeg",
  "Tuberose Absolute": "/images/ingredients/TuberoseAbsolute.jpeg",
  "Orris Butter Tincture": "/images/ingredients/OrrisButterTincture.jpeg",
  "Clearwood®": "/images/ingredients/Clearwood.jpeg",
  "Iso E Super": "/images/ingredients/ISOESuper.jpeg",
  "Woody Base (Pellwall)": "/images/ingredients/WoodyBase.jpeg",
  Koavone: "/images/ingredients/Koavone.jpeg",
  Bornafix: "/images/ingredients/Bornafix.jpeg",
  Timbersilk: "/images/ingredients/Timbersilk.jpeg",
  "BHT Crystals": "/images/ingredients/BHTCrystals.jpeg",
  Veramoss: "/images/ingredients/Veramoss.jpeg",
  "1-Octen-3-ol": "/images/ingredients/1Octen3ol.tn.jpeg",
  "Castoreum Absolute": "/images/ingredients/Castoreum.jpeg",
  "Neroli Tunisia P&N": "/images/ingredients/NeroliTunisiaPN.jpeg",
  Civettone: "/images/ingredients/Civettone.jpeg",
  "Ysamber K": "/images/ingredients/YSamberK.jpeg",
  "Vetiveryl Acetat": "/images/ingredients/VetiverylAcetat.jpeg",
  "Aldehyde C-10": "/images/ingredients/AldehydC10.tn.jpeg",
  "Aldehyde C-12 MNA": "/images/ingredients/AldehydeC12.tn.jpeg",
  "Aldehyde C-8": "/images/ingredients/AldehydC8.tn.jpeg",
  Amarocit: "/images/ingredients/Amarocit.tn.jpeg",
  "Amber Xtreme": "/images/ingredients/AmberXtreme.tn.jpeg",
  Ambercore: "/images/ingredients/AmberCore.tn.jpeg",
  "Ambergris T Oliffac": "/images/ingredients/Ambergris.jpeg",
  Ambrettolide: "/images/ingredients/Ambrettolide.jpeg",
  Ambroxan: "/images/ingredients/Ambroxan.jpeg",
  Aphermate: "/images/ingredients/Aphermate.jpeg",
  Aquaflor: "/images/ingredients/Aquaflor.jpeg",
  "Beeswax Absolute": "/images/ingredients/BeeswaxAbsolute.jpeg",
  "Bergamot - Essential Oil - Calabria, IT":
    "/images/ingredients/BergamotEO.jpeg",
  "Beta Pinene": "/images/ingredients/BetaPinene.jpeg",
  "Beyond Hivernal": "/images/ingredients/BeyondHivernal.jpeg",
  "Birch Tar (Rectified)": "/images/ingredients/BirchTar.jpeg",
  "Black Hemlock Absolute": "/images/ingredients/BlackHemlock.jpeg",
  "Blackcurrant Absolute": "/images/ingredients/BlackcurrantAbsolute.jpeg",
  "Broom Absolute": "/images/ingredients/BroomAbsolute.tn.jpeg",
  Calone: "/images/ingredients/Calone.tn.jpeg",
  Cashmeran: "/images/ingredients/Cashmeran.tn.jpeg",
  "Cistus Oil": "/images/ingredients/CistusOil.tn.jpeg",
  "Cypress EO": "/images/ingredients/CypressEO.tn.jpeg",
  Evernyl: "/images/ingredients/Evernyl.tn.jpeg",
  "Fir Balsam": "/images/ingredients/FirBalsam.tn.jpeg",
  "Methyl Anthranilate": "/images/ingredients/MethylAnthranilate.tn.jpeg",
  "Methyl Ionone Gamma": "/images/ingredients/MethylIononeGamma.tn.jpeg",
  "Methyl Laitone": "/images/ingredients/MethylLaitone.tn.jpeg",
  "Mimosa Olessence": "/images/ingredients/MimosaOlessence.tn.jpeg",
} as Record<string, string>;

export const formulas = {
  "Orange Woods": [
    "/images/perfumes/orangewoods.jpg",
    "/images/perfumes/orangewoods-1.jpg",
    "/images/perfumes/orangewoods-2.jpg",
    "/images/perfumes/orangewoods-3.jpg",
    "/images/perfumes/orangewoods-4.jpg",
    "/images/perfumes/orangewoods-5.jpg",
    "/images/perfumes/orangewoods-6.jpg",
    "/images/perfumes/orangewoods-7.jpg",
  ],
  'Riviera Bloom OFA': [
    "/images/perfumes/rivierabloomofa.jpg",
  ]
} as Record<string, string[]>;
