import { normalize } from "@/utils/perfumersApprentice";
import { NormalizedItem } from "libperfumery/dist/types/NormalizedItem";

import pa from "libperfumery/dist/static/data/normalized/pa";
import pw from "libperfumery/dist/static/data/normalized/pw";

export const getPrice = (entry: Pick<NormalizedItem, "price">) => {
  return Number(entry.price?.replace(/[$€£]/, "") || 0);
};
const perfumersApprentice = pa
  .flat(3)
  .filter((itm) => itm?.size && itm?.price)
  .map((itm) => ({ ...itm, source: "PA" })) as unknown as NormalizedItem[];

console.log("PA ", pa, perfumersApprentice);
const pellwall = pw
  .flat(3)
  .filter((itm) => itm?.size && itm?.price)
  .map((itm) => ({ ...itm, source: "PW" })) as unknown as NormalizedItem[];

const inventory: NormalizedItem[] = [
  {
    amount: "500g",
    quantity: 1,
    title: "Koavone",
    dilution: "100%",
    price: "34$",
    id: 835,
  },
  {
    amount: "500g",
    quantity: 1,
    title: "Vetiveryl Acetat",
    dilution: "100%",
    price: "247$",
    id: 837,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Cedryl Acetat",
    dilution: "100%",
    price: "23$",
    id: 839,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Birch Tar (Rectified)",
    dilution: "100%",
    price: "20$",
    id: 842,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Vertenex",
    dilution: "100%",
    price: "11$",
    id: 843,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Vetikone",
    dilution: "100%",
    price: "12$",
    id: 844,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Isolongifolanone",
    dilution: "100%",
    price: "22$",
    id: 845,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Octyl Acetate",
    dilution: "100%",
    price: "18$",
    id: 846,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Fir Balsam",
    dilution: "100%",
    price: "27$",
    id: 847,
    onStock: true,
  },
  {
    amount: "60ml",
    quantity: 1,
    title: "Fir Balsam",
    dilution: "100%",
    price: "92$",
    id: 848,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Oakwood Absolute ",
    dilution: "50%",
    price: "40$",
    id: 849,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Eucalyptus Bioabsolute",
    dilution: "100%",
    price: "17$",
    id: 850,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Z11 10 MIP",
    dilution: "100%",
    price: "28$",
    id: 851,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Timbrox Base",
    dilution: "100%",
    price: "47$",
    id: 852,
    onStock: true,
  },
  {
    amount: "30g",
    quantity: 1,
    title: "Olibanum Absolute",
    dilution: "100%",
    price: "13$",
    id: 853,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Sandalwood Mysore",
    dilution: "100%",
    price: "90$",
    id: 855,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Tolu Balsam Essence",
    dilution: "100%",
    price: "8$",
    id: 856,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Pino Acetaldehyde",
    dilution: "100%",
    price: "45$",
    id: 857,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Beta Pinene",
    dilution: "100%",
    price: "11$",
    id: 858,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Oakmoss Absolute",
    dilution: "100%",
    price: "24$",
    id: 860,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Oakmoss Absolute",
    dilution: "10%",
    price: "14$",
    id: 861,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Dirt Fragrance Oil",
    dilution: "100%",
    price: "13$",
    id: 862,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Terrasol",
    dilution: "100%",
    price: "142$",
    id: 863,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Kephalis",
    dilution: "100%",
    price: "20$",
    id: 864,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Galbanum Oil",
    dilution: "100%",
    price: "22$",
    id: 865,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Galbanum Resinoid",
    dilution: "100%",
    price: "23$",
    id: 866,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Costus Oliffac",
    dilution: "100%",
    price: "20$",
    id: 867,
    onStock: true,
  },
  {
    amount: "200ml",
    quantity: 1,
    title: "Dowanol",
    dilution: "100%",
    price: "27$",
    id: 869,
    onStock: false,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Iralia",
    dilution: "100%",
    price: "67$",
    id: 870,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Hedione",
    dilution: "100%",
    price: "16$",
    id: 871,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Hedione HC",
    dilution: "100%",
    price: "24$",
    id: 872,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Scentenal",
    dilution: "100%",
    price: "16$",
    id: 873,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Calone",
    dilution: "10%",
    price: "14$",
    id: 874,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Maritima",
    dilution: "100%",
    price: "24$",
    id: 875,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Seaweed Absolute ",
    dilution: "50%",
    price: "24$",
    id: 876,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Ethylene Brassylate",
    dilution: "100%",
    price: "20$",
    id: 877,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Galaxolide",
    dilution: "50%",
    price: "35$",
    id: 878,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Cashmeran",
    dilution: "100%",
    price: "61$",
    id: 879,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Habanolide",
    dilution: "100%",
    price: "45$",
    id: 880,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Velvione",
    dilution: "100%",
    price: "57$",
    id: 881,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Muscenone",
    dilution: "100%",
    price: "65$",
    id: 882,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Exaltolide",
    dilution: "100%",
    price: "18$",
    id: 883,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Celestolide",
    dilution: "100%",
    price: "18$",
    id: 884,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Ambrettolide",
    dilution: "100%",
    price: "62$",
    id: 885,
  },
  {
    amount: "80g",
    quantity: 1,
    title: "Musk Ketone",
    dilution: "100%",
    price: "11$",
    id: 886,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Fixateur 505E ",
    dilution: "100%",
    price: "24$",
    id: 887,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Civettone ",
    dilution: "100%",
    price: "77$",
    id: 888,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Ambroxan",
    dilution: "10%",
    price: "77$",
    id: 889,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Vertofix Coeur",
    dilution: "100%",
    price: "52$",
    id: 891,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Ambercore",
    dilution: "100%",
    price: "22$",
    id: 892,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Sylvamber",
    dilution: "100%",
    price: "14$",
    id: 893,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Ambergris T Oliffac",
    dilution: "100%",
    price: "31$",
    id: 894,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Civet Absolute",
    dilution: "100%",
    price: "31$",
    id: 895,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Amber Xtreme",
    dilution: "100%",
    price: "19$",
    id: 896,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Castoreum Absolute ",
    dilution: "100%",
    price: "38$",
    id: 897,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Bergamot - Essential Oil - Calabria, IT",
    dilution: "100%",
    price: "13$",
    id: 898,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Rose Givco 217",
    dilution: "100%",
    price: "27$",
    id: 899,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Orange Flower Absolute",
    dilution: "100%",
    price: "152$",
    id: 902,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Neroli Tunisia P&N",
    dilution: "100%",
    price: "61$",
    id: 903,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Cistus Oil",
    dilution: "100%",
    price: "63$",
    id: 904,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Violet Leaf Absolute",
    dilution: "100%",
    price: "20$",
    id: 906,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Broom Absolute",
    dilution: "100%",
    price: "79$",
    id: 907,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Jasmine Sambac Absolute ",
    dilution: "100%",
    price: "36$",
    id: 910,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Jasmine Grandiflorum Absolute",
    dilution: "100%",
    price: "33$",
    id: 911,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Blackcurrant Absolute",
    dilution: "100%",
    price: "25$",
    id: 913,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Mimosa Olessence",
    dilution: "100%",
    price: "99$",
    id: 914,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Labdanum Absolute",
    dilution: "100%",
    price: "29$",
    id: 916,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Beeswax Absolute",
    dilution: "100%",
    price: "50$",
    id: 917,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Bran Absolute",
    dilution: "100%",
    price: "13$",
    id: 918,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Black Hemlock Absolute",
    dilution: "100%",
    price: "26$",
    id: 919,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Heliotropin Replacer",
    dilution: "100%",
    price: "6$",
    id: 920,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Methyl Laitone",
    dilution: "10%",
    price: "7$",
    id: 921,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Linalool",
    dilution: "100%",
    price: "13$",
    id: 922,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Vernaldehyde",
    dilution: "100%",
    price: "16$",
    id: 923,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Methyl Ionone Gamma",
    dilution: "100%",
    id: 924,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Coumarin",
    dilution: "10%",
    price: "15$",
    id: 925,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Farnesol",
    dilution: "100%",
    price: "9$",
    id: 927,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Mate Absolute",
    dilution: "100%",
    price: "12$",
    id: 928,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Aldehyde C-8",
    dilution: "100%",
    price: "10$",
    id: 929,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Aldehyde C-10",
    dilution: "100%",
    price: "11$",
    id: 930,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Aldehyde C-12 MNA ",
    dilution: "10%",
    price: "13$",
    id: 931,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Orange Flower Blend",
    dilution: "100%",
    price: "27€",
    id: 935,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Cistus Oil ",
    dilution: "100%",
    price: "20$",
    id: 937,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Clearwood®",
    dilution: "100%",
    price: "5$",
    id: 938,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Precyclemone B",
    dilution: "100%",
    price: "6$",
    id: 944,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Sandalwood Mysore ",
    dilution: "100%",
    price: "25$",
    id: 946,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Methyl Laitone ",
    dilution: "10%",
    price: "4$",
    id: 947,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Beeswax Absolute ",
    dilution: "100%",
    price: "16$",
    id: 948,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Ambroxan ",
    dilution: "10%",
    price: "27$",
    id: 949,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Terrasol",
    dilution: "100%",
    price: "24$",
    id: 950,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Patchouli EO",
    dilution: "100%",
    price: "6€",
    id: 951,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Patchouli Light EO",
    dilution: "100%",
    price: "6€",
    id: 952,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Fir Balsam",
    dilution: "100%",
    price: "8€",
    id: 953,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Beta Pinene",
    dilution: "100%",
    price: "7€",
    id: 954,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Pino Acetaldehyde",
    dilution: "100%",
    price: "14€",
    id: 955,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Cedarwood EO",
    dilution: "100%",
    price: "8€",
    id: 956,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Sandalwood EO",
    dilution: "100%",
    price: "14€",
    id: 957,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Cypress EO",
    dilution: "100%",
    price: "10€",
    id: 958,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Pine Needles EO",
    dilution: "100%",
    price: "10€",
    id: 959,
    onStock: true,
  },
  {
    amount: "10g",
    quantity: 1,
    title: "Veramoss",
    dilution: "100%",
    price: "7€",
    id: 960,
    onStock: true,
  },
  {
    amount: "10g",
    quantity: 1,
    title: "Evernyl",
    dilution: "100%",
    price: "9€",
    id: 961,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Terrasol",
    dilution: "100%",
    price: "18€",
    id: 962,
    onStock: true,
  },
  {
    amount: "10g",
    quantity: 1,
    title: "Padma",
    dilution: "100%",
    price: "5€",
    id: 963,
    onStock: true,
  },
  {
    amount: "10g",
    quantity: 1,
    title: "Olibanum EO",
    dilution: "100%",
    price: "18€",
    id: 964,
    onStock: true,
  },
  {
    amount: "10g",
    quantity: 1,
    title: "Linalool Oxide",
    dilution: "100%",
    price: "6€",
    id: 965,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Cis-3-hexen-1-ol",
    dilution: "100%",
    price: "13€",
    id: 966,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Trital",
    dilution: "100%",
    price: "7€",
    id: 967,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "1-Octen-3-ol",
    dilution: "100%",
    price: "13€",
    id: 968,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Amarocit",
    dilution: "100%",
    price: "6€",
    id: 969,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Aphermate",
    dilution: "100%",
    price: "7€",
    id: 970,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Ozofleur",
    dilution: "100%",
    price: "9€",
    id: 971,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Seaweed Absolute ",
    dilution: "10%",
    price: "14€",
    id: 972,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Aquaflor",
    dilution: "100%",
    price: "14€",
    id: 973,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Hivernal",
    dilution: "100%",
    price: "18€",
    id: 974,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Beyond Hivernal",
    dilution: "100%",
    price: "7€",
    id: 975,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Calone",
    dilution: "100%",
    price: "14€",
    id: 976,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Ambroxan ",
    dilution: "10%",
    price: "7€",
    id: 977,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Sylvamber",
    dilution: "100%",
    price: "5€",
    id: 978,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Musk Blend (Pellwall)",
    dilution: "100%",
    price: "13€",
    id: 979,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Galaxolide",
    dilution: "50%",
    price: "4€",
    id: 980,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Tonalid",
    dilution: "100%",
    price: "6€",
    id: 981,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Timbersilk",
    dilution: "100%",
    price: "4€",
    id: 982,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Z11 10 MIP",
    dilution: "100%",
    price: "8€",
    id: 983,
    onStock: true,
  },
  {
    amount: "20ml",
    quantity: 1,
    title: "Ambrettolide",
    dilution: "100%",
    price: "25€",
    id: 984,
    onStock: true,
  },
  {
    amount: "20ml",
    quantity: 1,
    title: "Coumarin",
    dilution: "100%",
    price: "8€",
    id: 985,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Myrrh Oil",
    dilution: "100%",
    price: "12€",
    id: 987,
    onStock: true,
  },
  {
    amount: "100ml",
    quantity: 1,
    title: "Lavender EO",
    dilution: "100%",
    price: "11€",
    id: 988,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Vertofix Coeur",
    dilution: "100%",
    price: "6€",
    id: 989,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Floralozone",
    dilution: "100%",
    price: "5€",
    id: 990,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Helional",
    dilution: "100%",
    price: "8€",
    id: 991,
    onStock: true,
  },
  {
    amount: "20ml",
    quantity: 1,
    title: "Hedione",
    dilution: "100%",
    price: "6€",
    id: 993,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Methyl Anthranilate ",
    dilution: "50%",
    price: "10$",
    id: 994,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Labdanum Absolute",
    dilution: "50%",
    price: "7$",
    id: 995,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Ambergris T Oliffac",
    dilution: "100%",
    price: "12$",
    id: 996,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Rose Givco 217",
    dilution: "100%",
    price: "18$",
    id: 997,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Lavender Absolute",
    dilution: "100%",
    price: "28$",
    id: 998,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Lavender Absolute",
    dilution: "100%",
    price: "77$",
    id: 999,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Iralia",
    dilution: "100%",
    price: "25$",
    id: 1000,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Maritima",
    dilution: "100%",
    price: "9$",
    id: 1002,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Oud Assafi™",
    dilution: "5%",
    price: "147$",
    id: 1005,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Orange Flower Absolute",
    dilution: "100%",
    price: "44$",
    id: 1010,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Orange Flower Absolute",
    dilution: "10%",
    price: "33€",
    id: 1011,
    onStock: true,
  },
  {
    amount: "10ml",
    quantity: 1,
    title: "Geosmin",
    dilution: "10%",
    price: "72€",
    id: 1012,
    onStock: true,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Rose Oil, Bulgarian P&N",
    dilution: "100%",
    price: "99$",
    id: 1013,
  },
  {
    amount: "4ml",
    quantity: 1,
    title: "Tuberose Absolute",
    dilution: "100%",
    price: "97$",
    id: 1014,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Clearwood®",
    dilution: "100%",
    price: "40$",
    id: 1015,
    onStock: true,
  },
  {
    amount: "500g",
    quantity: 1,
    title: "Clearwood®",
    dilution: "100%",
    price: "64$",
    id: 1016,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Orris Butter Tincture",
    dilution: "20%",
    price: "69$",
    id: 1017,
    onStock: true,
  },
  {
    amount: "15ml",
    quantity: 1,
    title: "Rose Oil, Bulgarian P&N",
    dilution: "10%",
    price: "34$",
    id: 1018,
    onStock: true,
  },
  {
    amount: "500g",
    quantity: 1,
    title: "Iso E Super",
    dilution: "100%",
    price: "32€",
    id: 1019,
    onStock: true,
  },
  {
    amount: "50g",
    quantity: 1,
    title: "Iso E Super",
    dilution: "100%",
    price: "9€",
    id: 1020,
    onStock: true,
  },
  {
    amount: "500g",
    quantity: 1,
    title: "Woody Base (Pellwall)",
    dilution: "100%",
    price: "188€",
    id: 1021,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Koavone",
    dilution: "100%",
    price: "22$",
    id: 1022,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Vetiveryl Acetat",
    dilution: "100%",
    price: "137$",
    id: 1023,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Bornafix",
    dilution: "100%",
    price: "39$",
    id: 1024,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Ysamber K",
    dilution: "100%",
    price: "57$",
    id: 1025,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Veramoss",
    dilution: "100%",
    price: "43$",
    id: 1026,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "Timbersilk",
    dilution: "100%",
    price: "32$",
    id: 1027,
    onStock: true,
  },
  {
    amount: "250g",
    quantity: 1,
    title: "BHT Crystals",
    dilution: "100%",
    price: "33$",
    id: 1028,
    onStock: true,
  },
]
  .map((itm) => {
    const norm = [...perfumersApprentice, ...pellwall].find(
      (paItm) =>
        paItm.title.trim() === itm.title.trim() &&
        (paItm as any).size === itm.amount
    );

    if (norm) return norm;
    if (!itm.price || !itm.amount) return;
    if (!norm)
      return normalize({
        ...itm,
        size: itm.amount,
        attributes: [],
        source: "?",
      });
    return norm;
  })
  .filter((ele) => ele?.price) as unknown as NormalizedItem[];

export { pellwall, perfumersApprentice, inventory };
