import { normalize } from "@/utils/perfumersApprentice";
import { NormalizedItem } from "libperfumery/dist/types/NormalizedItem";

import pa from "libperfumery/dist/static/data/normalized/pa";
import pw from "libperfumery/dist/static/data/normalized/pw";

export const getPrice = (entry: Pick<NormalizedItem, "price">) => {
  return Number(entry.price?.replace(/[$€£]/, "") || 0);
};
const perfumersApprentice = pa
  .flat(3)
  .filter((itm) => itm?.size && itm?.price)
  .map((itm) => ({ ...itm, source: "PA" })) as unknown as NormalizedItem[];

const pellwall = pw
  .flat(3)
  .filter((itm) => itm?.size && itm?.price)
  .map((itm) => ({ ...itm, source: "PW" })) as unknown as NormalizedItem[];

const inventory: NormalizedItem[] = [
  {
    amount: "500g",
    title: "Koavone",
    dilution: "100%",
    price: "34$",
  },
  {
    amount: "500g",
    title: "Vetiveryl Acetat",
    dilution: "100%",
    price: "247$",
  },
  {
    amount: "250g",
    title: "Cedryl Acetat",
    dilution: "100%",
    price: "23$",
  },
  {
    amount: "50g",
    title: "Birch Tar (Rectified)",
    dilution: "100%",
    price: "20$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Vertenex",
    dilution: "100%",
    price: "11$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Vetikone",
    dilution: "100%",
    price: "12$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Isolongifolanone",
    dilution: "100%",
    price: "22$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Octyl Acetate",
    dilution: "100%",
    price: "18$",
  },
  {
    amount: "15ml",
    title: "Fir Balsam",
    dilution: "100%",
    price: "27$",
    onStock: true,
  },
  {
    amount: "60ml",
    title: "Fir Balsam",
    dilution: "100%",
    price: "92$",
  },
  {
    amount: "15ml",
    title: "Oakwood Absolute ",
    dilution: "50%",
    price: "40$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Eucalyptus Bioabsolute",
    dilution: "100%",
    price: "17$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Z11 10 MIP",
    dilution: "100%",
    price: "28$",
  },
  {
    amount: "50g",
    title: "Timbrox Base",
    dilution: "100%",
    price: "47$",
    onStock: true,
  },
  {
    amount: "30g",
    title: "Olibanum Absolute",
    dilution: "100%",
    price: "13$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Sandalwood Mysore",
    dilution: "100%",
    price: "90$",
  },
  {
    amount: "15ml",
    title: "Tolu Balsam Essence",
    dilution: "100%",
    price: "8$",
  },
  {
    amount: "50g",
    title: "Pino Acetaldehyde",
    dilution: "100%",
    price: "45$",
  },
  {
    amount: "50g",
    title: "Beta Pinene",
    dilution: "100%",
    price: "11$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Oakmoss Absolute",
    dilution: "100%",
    price: "24$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Oakmoss Absolute",
    dilution: "10%",
    price: "14$",
  },
  {
    amount: "50g",
    title: "Dirt Fragrance Oil",
    dilution: "100%",
    price: "13$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Terrasol",
    dilution: "100%",
    price: "142$",
  },
  {
    amount: "50g",
    title: "Kephalis",
    dilution: "100%",
    price: "20$",
  },
  {
    amount: "15ml",
    title: "Galbanum Oil",
    dilution: "100%",
    price: "22$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Galbanum Resinoid",
    dilution: "100%",
    price: "23$",
  },
  {
    amount: "15ml",
    title: "Costus Oliffac",
    dilution: "100%",
    price: "20$",
    onStock: true,
  },
  {
    amount: "200ml",
    title: "Dowanol",
    dilution: "100%",
    price: "27$",
    onStock: false,
  },
  {
    amount: "50g",
    title: "Iralia",
    dilution: "100%",
    price: "67$",
  },
  {
    amount: "50g",
    title: "Hedione",
    dilution: "100%",
    price: "16$",
  },
  {
    amount: "15ml",
    title: "Hedione HC",
    dilution: "100%",
    price: "24$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Scentenal",
    dilution: "100%",
    price: "16$",
  },
  {
    amount: "50g",
    title: "Calone",
    dilution: "10%",
    price: "14$",
  },
  {
    amount: "15ml",
    title: "Maritima",
    dilution: "100%",
    price: "24$",
  },
  {
    amount: "4ml",
    title: "Seaweed Absolute ",
    dilution: "50%",
    price: "24$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Ethylene Brassylate",
    dilution: "100%",
    price: "20$",
  },
  {
    amount: "250g",
    title: "Galaxolide",
    dilution: "50%",
    price: "35$",
  },
  {
    amount: "250g",
    title: "Cashmeran",
    dilution: "100%",
    price: "61$",
  },
  {
    amount: "250g",
    title: "Habanolide",
    dilution: "100%",
    price: "45$",
  },
  {
    amount: "50g",
    title: "Velvione",
    dilution: "100%",
    price: "57$",
  },
  {
    amount: "50g",
    title: "Muscenone",
    dilution: "100%",
    price: "65$",
  },
  {
    amount: "50g",
    title: "Exaltolide",
    dilution: "100%",
    price: "18$",
  },
  {
    amount: "50g",
    title: "Celestolide",
    dilution: "100%",
    price: "18$",
  },
  {
    amount: "50g",
    title: "Ambrettolide",
    dilution: "100%",
    price: "62$",
  },
  {
    amount: "80g",
    title: "Musk Ketone",
    dilution: "100%",
    price: "11$",
  },
  {
    amount: "4ml",
    title: "Fixateur 505E ",
    dilution: "100%",
    price: "24$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Civettone ",
    dilution: "100%",
    price: "77$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Ambroxan",
    dilution: "10%",
    price: "77$",
  },
  {
    amount: "250g",
    title: "Vertofix Coeur",
    dilution: "100%",
    price: "52$",
  },
  {
    amount: "50g",
    title: "Ambercore",
    dilution: "100%",
    price: "22$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Sylvamber",
    dilution: "100%",
    price: "14$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Ambergris T Oliffac",
    dilution: "100%",
    price: "31$",
  },
  {
    amount: "15ml",
    title: "Civet Absolute",
    dilution: "100%",
    price: "31$",
  },
  {
    amount: "15ml",
    title: "Amber Xtreme",
    dilution: "100%",
    price: "19$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Castoreum Absolute ",
    dilution: "100%",
    price: "38$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Bergamot - Essential Oil - Calabria, IT",
    dilution: "100%",
    price: "13$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Rose Givco 217",
    dilution: "100%",
    price: "27$",
  },
  {
    amount: "15ml",
    title: "Orange Flower Absolute",
    dilution: "100%",
    price: "152$",
  },
  {
    amount: "4ml",
    title: "Neroli Tunisia P&N",
    dilution: "100%",
    price: "61$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Cistus Oil",
    dilution: "100%",
    price: "63$",
  },
  {
    amount: "4ml",
    title: "Violet Leaf Absolute",
    dilution: "100%",
    price: "20$",
  },
  {
    amount: "4ml",
    title: "Broom Absolute",
    dilution: "100%",
    price: "79$",
  },
  {
    amount: "4ml",
    title: "Jasmine Sambac Absolute ",
    dilution: "100%",
    price: "36$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Jasmine Grandiflorum Absolute",
    dilution: "100%",
    price: "33$",
  },
  {
    amount: "4ml",
    title: "Blackcurrant Absolute",
    dilution: "100%",
    price: "25$",
  },
  {
    amount: "15ml",
    title: "Mimosa Olessence",
    dilution: "100%",
    price: "99$",
  },
  {
    amount: "50g",
    title: "Labdanum Absolute",
    dilution: "100%",
    price: "29$",
  },
  {
    amount: "15ml",
    title: "Beeswax Absolute",
    dilution: "100%",
    price: "50$",
  },
  {
    amount: "15ml",
    title: "Bran Absolute",
    dilution: "100%",
    price: "13$",
  },
  {
    amount: "15ml",
    title: "Black Hemlock Absolute",
    dilution: "100%",
    price: "26$",
  },
  {
    amount: "15ml",
    title: "Heliotropin Replacer",
    dilution: "100%",
    price: "6$",
  },
  {
    amount: "15ml",
    title: "Methyl Laitone",
    dilution: "10%",
    price: "7$",
  },
  {
    amount: "50g",
    title: "Linalool",
    dilution: "100%",
    price: "13$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Vernaldehyde",
    dilution: "100%",
    price: "16$",
  },
  {
    amount: "50g",
    title: "Methyl Ionone Gamma",
    dilution: "100%",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Coumarin",
    dilution: "10%",
    price: "15$",
  },
  {
    amount: "15ml",
    title: "Farnesol",
    dilution: "100%",
    price: "9$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Mate Absolute",
    dilution: "100%",
    price: "12$",
  },
  {
    amount: "50g",
    title: "Aldehyde C-8",
    dilution: "100%",
    price: "10$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Aldehyde C-10",
    dilution: "100%",
    price: "11$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Aldehyde C-12 MNA ",
    dilution: "10%",
    price: "13$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Orange Flower Blend",
    dilution: "100%",
    price: "27€",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Cistus Oil ",
    dilution: "100%",
    price: "20$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Clearwood®",
    dilution: "100%",
    price: "5$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Precyclemone B",
    dilution: "100%",
    price: "6$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Sandalwood Mysore ",
    dilution: "100%",
    price: "25$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Methyl Laitone ",
    dilution: "10%",
    price: "4$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Beeswax Absolute ",
    dilution: "100%",
    price: "16$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Ambroxan ",
    dilution: "10%",
    price: "27$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Terrasol",
    dilution: "100%",
    price: "24$",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Patchouli EO",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Patchouli Light EO",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Fir Balsam",
    dilution: "100%",
    price: "8€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Beta Pinene",
    dilution: "100%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Pino Acetaldehyde",
    dilution: "100%",
    price: "14€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Cedarwood EO",
    dilution: "100%",
    price: "8€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Sandalwood EO",
    dilution: "100%",
    price: "14€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Cypress EO",
    dilution: "100%",
    price: "10€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Pine Needles EO",
    dilution: "100%",
    price: "10€",
    onStock: true,
  },
  {
    amount: "10g",
    title: "Veramoss",
    dilution: "100%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10g",
    title: "Evernyl",
    dilution: "100%",
    price: "9€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Terrasol",
    dilution: "100%",
    price: "18€",
    onStock: true,
  },
  {
    amount: "10g",
    title: "Padma",
    dilution: "100%",
    price: "5€",
    onStock: true,
  },
  {
    amount: "10g",
    title: "Olibanum EO",
    dilution: "100%",
    price: "18€",
    onStock: true,
  },
  {
    amount: "10g",
    title: "Linalool Oxide",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Cis-3-hexen-1-ol",
    dilution: "100%",
    price: "13€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Trital",
    dilution: "100%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "1-Octen-3-ol",
    dilution: "100%",
    price: "13€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Amarocit",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Aphermate",
    dilution: "100%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Ozofleur",
    dilution: "100%",
    price: "9€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Seaweed Absolute ",
    dilution: "10%",
    price: "14€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Aquaflor",
    dilution: "100%",
    price: "14€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Hivernal",
    dilution: "100%",
    price: "18€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Beyond Hivernal",
    dilution: "100%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Calone",
    dilution: "100%",
    price: "14€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Ambroxan ",
    dilution: "10%",
    price: "7€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Sylvamber",
    dilution: "100%",
    price: "5€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Musk Blend (Pellwall)",
    dilution: "100%",
    price: "13€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Galaxolide",
    dilution: "50%",
    price: "4€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Tonalid",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Timbersilk",
    dilution: "100%",
    price: "4€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Z11 10 MIP",
    dilution: "100%",
    price: "8€",
    onStock: true,
  },
  {
    amount: "20ml",
    title: "Ambrettolide",
    dilution: "100%",
    price: "25€",
    onStock: true,
  },
  {
    amount: "20ml",
    title: "Coumarin",
    dilution: "100%",
    price: "8€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Myrrh Oil",
    dilution: "100%",
    price: "12€",
    onStock: true,
  },
  {
    amount: "100ml",
    title: "Lavender EO",
    dilution: "100%",
    price: "11€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Vertofix Coeur",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Floralozone",
    dilution: "100%",
    price: "5€",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Helional",
    dilution: "100%",
    price: "8€",
    onStock: true,
  },
  {
    amount: "20ml",
    title: "Hedione",
    dilution: "100%",
    price: "6€",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Methyl Anthranilate ",
    dilution: "50%",
    price: "10$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Labdanum Absolute",
    dilution: "50%",
    price: "7$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Ambergris T Oliffac",
    dilution: "100%",
    price: "12$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Rose Givco 217",
    dilution: "100%",
    price: "18$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Lavender Absolute",
    dilution: "100%",
    price: "28$",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Lavender Absolute",
    dilution: "100%",
    price: "77$",
  },
  {
    amount: "15ml",
    title: "Iralia",
    dilution: "100%",
    price: "25$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Maritima",
    dilution: "100%",
    price: "9$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Oud Assafi™",
    dilution: "5%",
    price: "147$",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Orange Flower Absolute",
    dilution: "100%",
    price: "44$",
    onStock: true,
  },
  {
    amount: "10ml",
    title: "Orange Flower Absolute",
    dilution: "10%",
    price: "33€",
    onStock: false,
    source: "PW",
  },
  {
    amount: "10ml",
    title: "Geosmin",
    dilution: "10%",
    price: "72€",
    onStock: true,
  },
  {
    amount: "4ml",
    title: "Rose Oil, Bulgarian P&N",
    dilution: "100%",
    price: "99$",
  },
  {
    amount: "4ml",
    title: "Tuberose Absolute",
    dilution: "100%",
    price: "97$",
  },
  {
    amount: "250g",
    title: "Clearwood®",
    dilution: "100%",
    price: "40$",
    onStock: true,
  },
  {
    amount: "500g",
    title: "Clearwood®",
    dilution: "100%",
    price: "64$",
  },
  {
    amount: "15ml",
    title: "Orris Butter Tincture",
    dilution: "20%",
    price: "69$",
    onStock: true,
  },
  {
    amount: "15ml",
    title: "Rose Oil, Bulgarian P&N",
    dilution: "10%",
    price: "34$",
    onStock: true,
  },
  {
    amount: "500g",
    title: "Iso E Super",
    dilution: "100%",
    price: "32€",
    onStock: true,
  },
  {
    amount: "50g",
    title: "Iso E Super",
    dilution: "100%",
    price: "9€",
    onStock: true,
  },
  {
    amount: "500g",
    title: "Woody Base (Pellwall)",
    dilution: "100%",
    price: "188€",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Koavone",
    dilution: "100%",
    price: "22$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Vetiveryl Acetat",
    dilution: "100%",
    price: "137$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Bornafix",
    dilution: "100%",
    price: "39$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Ysamber K",
    dilution: "100%",
    price: "57$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Veramoss",
    dilution: "100%",
    price: "43$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "Timbersilk",
    dilution: "100%",
    price: "32$",
    onStock: true,
  },
  {
    amount: "250g",
    title: "BHT Crystals",
    dilution: "100%",
    price: "33$",
    onStock: true,
  },
]
  .map((itm) => {
    const norm = [...perfumersApprentice, ...pellwall].find(
      (paItm) =>
        paItm.title.trim() === itm.title.trim() &&
        (paItm as any).size === itm.amount
    );

    if (norm) return norm;
    if (!itm.price || !itm.amount) return;
    if (!norm)
      return normalize({
        ...itm,
        size: itm.amount,
        attributes: [],
        source: itm.source || "N/A",
      });
    return norm;
  })
  .filter((ele) => ele?.price) as unknown as NormalizedItem[];

export { pellwall, perfumersApprentice, inventory };
