import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "http://localhost:4000",
  documents: ["src/apollo/queries/*.graphql"],
  generates: {
    "./src/apollo/__generated__/schema.types.ts": {
      plugins: [
        {
          add: {
            content: [
              "/* eslint-disable */",
              "/* ⚠️ DO NOT EDIT ⚠️ */",
              "/* This file is automatically generated, run 'yarn codegen' to update */",
            ],
          },
        },
        "typescript",
      ],
    },
    "./src/apollo/queries/generated/graphql.tsx": {
      presetConfig: {
        extension: ".tsx",
      },
      plugins: [
        {
          add: {
            content: `
// export type Maybe<T> = T | null;
// export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
// export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
// export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
            `,
          },
        },
        "typescript",
        "typescript-resolvers",
        "typescript-operations",
        "typescript-react-apollo",
      ],
      config: {
        withHooks: true,
      },
    },
  },
};

export default config;
